export type {
  AgentRunResult,
  AssetStatus,
  GeneratedAsset,
  Merchant,
  ModificationChanges,
  NotificationRow,
  Product,
  ProductSnapshot,
  Proposal,
  ProposalKind,
  ProposalPayload,
  ProposalStatus,
  SalesSummary,
  ShopifySyncResult,
} from "@/lib/api";
